name: Testing
on:
  push:
  pull_request:

jobs:
  cypress-test:
    name: Run on latest browsers
    runs-on: ubuntu-latest
    container: cypress/browsers:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cypress
        run: npm ci

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Run unit tests
        run: npm run test-headless
        continue-on-error: true



